//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_ENSAF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public int NCommande { get; set; }
        public int quantite { get; set; }
        public System.DateTime dateDemande { get; set; }
        public System.DateTime dateArrive { get; set; }
        public decimal prixGrossiere { get; set; }
        public int idFournisseur { get; set; }
        public int codeMagazin { get; set; }
        public int codeProduit { get; set; }
    
        public virtual Fournisseur Fournisseur { get; set; }
        public virtual Magazin Magazin { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
