//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_ENSAF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vente_magazin
    {
        public int idFacture { get; set; }
        public int codeProduit { get; set; }
        public int codeMagazin { get; set; }
        public int quantiteVendu { get; set; }
        public Nullable<System.DateTime> dateVente { get; set; }
    
        public virtual Magazin Magazin { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
